# Generated by Django 4.2.1 on 2024-03-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='classification',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
